### ISSUE TITLE
Attribution?

### ISSUE THREAD

**Issue by coffeeboo** [licensezero/licensezero-questions#14]
I understand this license may not be for libraries or small modules as much as OSS heavily-customizable apps or such, but neither licenses say anything about actually getting credit for work you made. Any plans to do so?

**Comment by kemitchell** [comment]
@coffeeboo Quite the contrary!

# Small Modules

License Zero's two public licenses---[Parity](https://github.com/licensezero/parity-public-license) and [Prosperity](https://github.com/licensezero/prosperity-public-license)---were written _specifically_ with small packages in mind! The [`licensezero` command](https://github.com/licensezero/cli) was written specifically to make handling lots of small License Zero dependencies in npm-based projects a snap.

The combination of those two pieces---licenses and CLI---make License Zero the first viable support system for folks writing lots of small, reusable pieces. Otherwise, following that development best-practice leaves contributors out of the funding and recognition that only comes with well known, top-line projects and applications that lend themselves naturally to foundations and fundraising drives.

In other words, License Zero was directly inspired by friends (and clients) of mine who've created a lot of small modules in the npm ecosystem. I won't mention them here. And they don't necessarily endorse License Zero.  But as far as I'm concerned, this work is for them.

# Attribution

As for attribution, or giving credit, both Parity and Prosperity include this rule:

> Ensure everyone who gets a copy of this software from you, 
> in source code or any other form, gets the text of this 
> license and the copyright and source notices above.

The notice lines look like:

> Copyright Notice: {{{name}}}
>
> Source Notice: {{{source}}}

Leaving space for a copyright notice, then requiring others who share copies of the software to include copies of that notice, is exactly how attribution works under MIT, BSD, and similar permissive licenses.

Here's the attribution language from the two-clause BSD license:

> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
>
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

And here's the language from The MIT License:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Notice that Parity and Prosperity _go one step further_, by requiring perservation of another notice line about where to find source, as well.  The `licensezero` command helps package developers write `LICENSE` files that fill the Source Notice line in with a URL of a page where others can find the source code for the package. Giving everyone access to the original source code helps protect the reputation of the original author. If someone gets a copy of your module with unfortunate changes, or a copy of an old version of your module, they can always use the Source Notice to compare the version they received from your version. The diff between your work and what they received isn't your fault!

**Comment by kemitchell** [comment]
[Here's an example](https://github.com/kemitchell/crgmw-diff.js/blob/4ed1841b83b384c843b485666a9add75cdcd2932/LICENSE) of a LICENSE file generated by the `licensezero` command line interface. Note that the "Copyright Notice" includes my name, as author, and that the "Source Notice" includes the URL of my GitHub repository, where you can find my source code.

**Comment by coffeeboo** [comment]
Alright, thanks! This definitely looks sustainable for something I'm releasing soon.

**Comment by kemitchell** [comment]
@coffeeboo feel free to drop me a line at kyle@artlessdevices.com, or open new issues here. I'll be happy to walk you through the process, and answer any more questions you have.
